<?php

include_once('ca_pacs.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_pacs_perm() {
  return array('ca_pacs change templates'); 
}

/**
 * Implementation of hook_menu().
 */
function ca_pacs_menu() {
  $items['admin/settings/ca_pacs'] = array(
    'title' => 'CA PACs: Admin',
    'description' => 'Change the look and feel of the ca_pacs module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_pacs_admin_settings_form'),
    'access arguments' => array('ca_pacs change templates'),
    'file' => 'ca_pacs.admin.inc',
    'file path' => drupal_get_path('module', 'ca_pacs') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function ca_pacs_action_info() {
  return array(
    'ca_pacs_add_pacs_administrator_action' => array(
      'type' => 'user',
      'description' => t('Add pacs admin role'),
    ),
    'ca_pacs_remove_pacs_administrator_action' => array(
      'type' => 'user',
      'description' => t('Remove pacs admin role'),
    ),
  );
}

function ca_pacs_add_pacs_administrator_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'pacs admin') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_pacs_add_pacs_administrator_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to PACs Admin',
  );
  return $form;
}

function ca_pacs_add_pacs_administrator_action_submit(&$form, &$form_state) {
  
}

function ca_pacs_remove_pacs_administrator_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'pacs admin') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_pacs_remove_pacs_administrator_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from PACs Admin',
  );
  return $form;
}

function ca_pacs_remove_pacs_administrator_action_submit(&$form, &$form_state) {
  
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_pacs_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_pacs_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_pacs' || $subtask['name'] == 'home' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_pacs') . "/css/ca_pacs.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_pacs_views_pre_render(&$view) {
  if ($view->name == 'lessons') {
    drupal_add_css(drupal_get_path('module', 'ca_pacs') . "/css/ca_pacs.css", 'module', 'all', FALSE);
  }
}
